name: Workflow Checker
description: Check if there are any other pending or in progress workflows for given runner lable
branding:
  icon: check-circle
  color: blue
inputs:
  token:
    description: 'GITHUB_TOKEN'
    required: true
  currentRunId:
    description: 'The run id of the current runner, required to exclude from results, pass in github.run_id'
    required: true
  runnerLabel:
    description: 'Lable to be checked for other running workflows'
    required: true
outputs:
  foundRunningJob:
    description: 'true if other running jobs have been found, false otherwise'
runs:
  using: 'node20'
  main: 'dist/index.js'
